packages/headless-driver/src/__tests__/index.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

[AMFlow](https://github.com/akashic-games/amflow/blob/master/src/AMFlow.ts) の仕様に合わせて `AMFLowStore` の実装を修正します。

Support multiple startPoints at AMFlow#put(get)StartPoint()

---

packages/headless-driver/src/__tests__/index.ts
packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts
packages/headless-driver/src/play/amflow/ErrorFactory.ts

AMFlowClient をリファクタリングします。
1. Active の AMFlow#onEvent() 呼び出し前に Passive から送信された Event を保存するように
2. [AMFlow側の仕様](https://github.com/akashic-games/amflow) より `Error#name` を定義に合わせる
3. すでに stop したプレーに紐付いていた `AMFlowClient#close()` を呼んだ際にエラーが発生していた件の修正

Refactor AMFlowClient

---

package-lock.json
packages/headless-driver-runner-v1/package.json
packages/headless-driver-runner-v1/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver-runner-v1/src/platform/assets/NodeTextAsset.ts
packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v2/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver-runner-v2/src/platform/assets/NodeTextAsset.ts
packages/headless-driver-runner/package-lock.json
packages/headless-driver-runner/package.json
packages/headless-driver-runner/src/Platform.ts
packages/headless-driver-runner/src/Runner.ts
packages/headless-driver-runner/src/index.ts
packages/headless-driver-runner/src/utils.ts
packages/headless-driver/package.json
packages/headless-driver/src/__tests__/AMFlowSpec.ts
packages/headless-driver/src/__tests__/PlaySpec.ts
packages/headless-driver/src/__tests__/constants.ts
packages/headless-driver/src/__tests__/fixtures/content-v2/content.json
packages/headless-driver/src/__tests__/fixtures/content-v2/game.json
packages/headless-driver/src/__tests__/helpers/MockRunnerManager.ts
packages/headless-driver/src/__tests__/helpers/SilentLogger.ts
packages/headless-driver/src/__tests__/runSpec.ts
packages/headless-driver/src/play/Content.ts
packages/headless-driver/src/play/Play.ts
packages/headless-driver/src/play/PlayManager.ts
packages/headless-driver/src/runner/RunnerManager.ts

* ローカルディレクトリの game.json から Runner を起動可能に
* テストが肥大化してきたので分割

Support to run local game.json

---

packages/headless-driver/src/__tests__/PlaySpec.ts
packages/headless-driver/src/play/AMFlowClientManager.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

PlayToken と permission を紐付けるマップ情報を AMFlowStore にもたせます。
それにより `AMFlowClientManager.ts > AMFlowClient > AMFlowStore` 間の循環参照を解決します。

Resolve circular dependency

---

packages/headless-driver-runner-v2/package.json

* engineFilesV2: 2.1.23
* engineFilesV1: 1.1.11

【v0.5.2】内部コンポーネントの更新(engineFiles@2.1.23, engineFiles@1.1.11)

---

packages/headless-driver-runner-v2/package.json

【v0.5.5】内部コンポーネントの更新(engineFiles@2.1.25, engineFiles@1.1.12)

---

packages/headless-driver-runner-v2/package.json

【v0.5.6】内部コンポーネントの更新(engineFiles@2.1.26, engineFiles@1.1.12)

---

packages/headless-driver-runner-v2/package.json

【v0.5.7】内部コンポーネントの更新(engineFiles@2.1.27, engineFiles@1.1.12)

---

packages/headless-driver-runner-v2/package.json

【v0.5.8】内部コンポーネントの更新(engineFiles@2.1.28, engineFiles@1.1.12)

---

packages/headless-driver-runner-v2/package.json

【v0.5.9】内部コンポーネントの更新(engineFiles@2.1.29, engineFiles@1.1.12)

---

packages/headless-driver-runner-v2/package.json

【v0.5.13】内部コンポーネントの更新(engineFiles@2.1.31, engineFiles@1.1.12)

---

packages/headless-driver-runner-v2/package.json

* engineFilesV2: 2.1.33
* engineFilesV1: 1.1.13
* playlog: 1.3.3
* trigger: 0.1.6

【v0.5.16】内部コンポーネントの更新(engineFiles@2.1.33, engineFiles@1.1.13)

---

packages/headless-driver-runner-v2/package.json

* engineFilesV2: 2.1.35
* engineFilesV1: 1.1.13
* playlog: 1.3.3
* trigger: 0.1.6

【v0.6.1】内部コンポーネントの更新(engineFiles@2.1.35, engineFiles@1.1.13)

---

packages/headless-driver-runner-v1/package.json
packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/package.json
packages/headless-driver-runner-v3/src/platform/NullAudioPlayer.ts
packages/headless-driver-runner/package.json
packages/headless-driver/package.json

* 内部コンポーネントの更新
* runner-v3のビルドが落ちていたので通るように修正

【v1.0.1】内部コンポーネントの更新(engineFiles@3.0.0-beta.2, engineFiles@2.1.37, engineFiles@1.1.14)とrunner-v3の修正

---

packages/headless-driver/src/play/PlayManager.ts
packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

akashic serveの `--debug-playlog` に渡すplaylog.jsonの `TickList[2]` の最初のフレームよりも、 `TickList[0]` の開始フレームが若い番号の場合、clientに渡るTickListの開始フレームが `TickList[2]` になってしまう現象があります。
これを解決するため、headless-driverに開始フレームを受け取る口を作り、serveコマンドの実行時にこれを呼ぶことで開始フレームを正しく扱えるように修正します。
https://github.com/akashic-games/akashic-cli/blob/master/packages/akashic-cli-serve/src/server/domain/PlayStore.ts#L172

add plaaylog I/F to createPlay

---

packages/headless-driver/src/runner/RunnerManager.ts

* コンテンツのgame.jsonに`environment`が定義されている且つ`environment["sandbox-runtime"]`が定義されていない場合runnerのversionがundefinedになってしまう不具合があったので修正する対応を行いました。

fix that runner-version will not be undefined

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner/src/Runner.ts
packages/headless-driver/src/__tests__/runSpec.ts
packages/headless-driver/src/runner/RunnerManager.ts

headless-driverに  `game.external` を与える機能の追加。
- `Runner#RunnerParameters`, `RunnerManager#CreateRunnerParameters` に  `externalValue`を追加。
- `externalValue` が存在する場合、`game.external` に `externalValue`の内容を追加します。

Add externalValue to Runner

---

packages/headless-driver-runner-v3/package.json
packages/headless-driver-runner-v3/src/platform/NullGlyphFactory.ts
packages/headless-driver-runner-v3/src/platform/NullRenderer.ts
packages/headless-driver-runner-v3/src/platform/ResourceFactory.ts

#137 の自動更新が失敗 (追従作業が必要) したので、対応します。 v3.0.0-beta.4 に追従したのみ。
* engineFilesV3: 3.0.0-beta.4
* engineFilesV2: 2.1.39

【v1.1.6】内部コンポーネントの更新(engineFiles@3.0.0-beta.4, engineFiles@2.1.39, engineFiles@1.1.14)

---

packages/headless-driver/package.json

掲題どおり。
Node.js に依存しているものの `@types/node` を入れておらず、孫依存で勝手にバージョンが上がってビルドできなくなっていました (string が `type BufferEncoding = "utf8" | ...` に変わった模様)。
ビルドが通っていたバージョンの `@types/node` を dependencies に加えます。

fix build problem around fs.readFileSync()

---

build/publishAndUpdateChangelog.js
package.json

* npm-scriptに記述している`publish:*`コマンドでこれまでタグの指定ができなかったので、環境変数を用いてタグの指定をできるようにしました。
* 環境変数`$PUBLISH_DIST_TAG`でpublish時のタグ名を指定できるようにしました
* デフォルト値はlatest(`publish:prerelease`コマンドのみnext)
* このコマンドはwindows環境では動かないと思われますが、windows環境でpublishする想定は無いのでこの対応で十分ではと判断しました(問題がある場合は修正します)

publishスクリプトにタグ指定オプションを追加

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 3.0.0-beta.7
* engineFilesV2: 2.1.43
* engineFilesV1: 1.1.15

【v1.1.26】内部コンポーネントの更新(engineFiles@3.0.0-beta.7, engineFiles@2.1.43, engineFiles@1.1.15)

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 3.0.0-beta.8
* engineFilesV2: 2.1.47

【v1.2.5】内部コンポーネントの更新(engineFiles@3.0.0-beta.8, engineFiles@2.1.47, engineFiles@1.1.16)

---

packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.0-beta.10
* engineFilesV2: 2.1.48

【v1.3.3】内部コンポーネントの更新(engineFiles@3.0.0-beta.10, engineFiles@2.1.48, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.0-beta.11
* engineFilesV2: 2.1.48

【v1.3.4】内部コンポーネントの更新(engineFiles@3.0.0-beta.11, engineFiles@2.1.48, engineFiles@1.1.16)

---

packages/headless-driver-runner/src/__tests__/LooperSpec.ts

環境によってテストが失敗するケースへの対応です。
呼び出しタイミングが保証されないsetTimeoutに替えて、jestがモックした関数を使うことで、実行時の安定化を行います。

use jest timer in LooperSpec

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 2.1.51
* engineFilesV2: 2.1.51

【v1.5.6】内部コンポーネントの更新(engineFiles@2.1.51, engineFiles@2.1.51, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.8
* engineFilesV2: 2.1.51

【v1.5.7】内部コンポーネントの更新(engineFiles@3.0.8, engineFiles@2.1.51, engineFiles@1.1.16)

---

package.json

* npm-scripts に`"publish:from-package"`の追加
* これを実行するとgithub上のpackage.jsonに記載されたversionでそのままpublishされる
* 通常はgithub上のpackage.jsonとnpm上のversionを同時に上げるので利用しないが、github上のpackage.jsonのversionしか上がらない等トラブルが発生した時に利用する想定

add publish script as npm-scripts

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 3.0.8
* engineFilesV2: 2.1.52

【v1.5.8】内部コンポーネントの更新(engineFiles@3.0.8, engineFiles@2.1.52, engineFiles@1.1.16)

---

packages/headless-driver-runner-v2/package.json

【v1.5.11】内部コンポーネントの更新(engineFiles@3.0.9, engineFiles@2.1.53, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.5.11】内部コンポーネントの更新(engineFiles@3.0.10, engineFiles@2.1.53, engineFiles@1.1.16)

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner/src/Runner.ts
packages/headless-driver/src/__tests__/runSpec.ts

akashic-engine のスクリプトアセット内で参照可能な `g` を利用側から参照できるようにします。

`g` の名前空間を export するように

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner/src/Runner.ts
packages/headless-driver/src/index.ts
packages/headless-driver/src/play/PlayManager.ts
packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts
packages/headless-driver/src/play/amflow/types.ts

* `Runner#platform` を公開プロパティに変更します。これにより利用側で `ResourceFactory ` へアクセスすることが可能になります。
* `DumpedPlaylog` を export します。
なし

`Runner#platform`, `DumpedPlaylog` を公開プロパティに変更

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner/src/Runner.ts

現状の PDI の API 仕様では `this.step()` による厳密なフレーム進行ができない。そこで、暫定的に `Runner#advanceUntil()`の内部で 1/2 フレームの時間ごとに step することでフレームが飛んでしまうことを防止する。

`Runner#advanceUntil()` の挙動を修正

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.18
* engineFilesV2: 2.1.54

【v1.8.2】内部コンポーネントの更新(engineFiles@3.0.18, engineFiles@2.1.54, engineFiles@1.1.16)

---

packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.18
* engineFilesV2: 2.1.55

【v1.8.3】内部コンポーネントの更新(engineFiles@3.0.18, engineFiles@2.1.55, engineFiles@1.1.16)

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
packages/headless-driver-runner/src/Runner.ts
packages/headless-driver/src/__tests__/renderer.spec.ts
packages/headless-driver/src/__tests__/runner.spec.ts

`Runner#start()` に引数 `{ paused?: boolean }` を追加します。
`paused` が真の場合はコンテンツの進行を停止した状態で `g.game` のインスタンスを返します 。

Add argument RunnerStartParameters of Runner#start()

---

packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/package.json
packages/headless-driver/package.json

【v1.9.2】内部コンポーネントの更新(engineFiles@3.0.20, engineFiles@2.1.57, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NodeTextAsset.ts

headless-driver-runner-v3 の  `NoteScriptAsset`,  `NodeTextAsset` で空文字を許容するようにします。
`if (!text){...` で空文字もはじかれてエラーとなるため、`text == null` に修正し空文字を許容します。

Fix runner-v3's NodeScriptAsset and NodeTextAsset to allow empty string

---

packages/headless-driver-runner-v3/package.json

【v1.9.6】内部コンポーネントの更新(engineFiles@3.0.22, engineFiles@2.1.57, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.9.7】内部コンポーネントの更新(engineFiles@3.1.0, engineFiles@2.1.57, engineFiles@1.1.16)

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v1/src/index.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v2/src/index.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner-v3/src/index.ts
packages/headless-driver/src/__tests__/runner.spec.ts

`RunnerV3_g` の型が `typeof g` となっていたのを `@akashic/engine-files` から直接 export するように修正します。
https://github.com/akashic-contents/templates/pull/5#discussion_r742568158 の件の対応となります。

fix: export `g` namespaces

---

CHANGELOG.md
package-lock.json
package.json

`headless-driver@2.0.0` のリリース準備です。
* akashic-cli-serve にて v1, v2, v3 コンテンツの実行まで確認
* headless-akashic にて結合テストが動作することを確認 (一部型の修正あり)

prepare v2.0.0

---

renovate.json

renovateがengine-filesのv1/v2系を更新しないようにします。
動作確認は https://github.com/kamakiri01/headless-driver/ で行いました。
この修正でDashboard https://github.com/kamakiri01/headless-driver/issues/1 のedit logから、engine-filesのPRが取り下げられたことが確認できます。
- なし

prevent aev1/aev2 update from renovate

---

CHANGELOG.md
package-lock.json
package.json

engine-files@3.2.2 に更新のため、version を 2.1.1 へあげます。
セルフマージとします。

Bump version 2.1.1

---

.github/workflows/release.yml
.github/workflows/test.yml
README.md
renovate.json

* `aev*` を自動更新するように修正します
* CI のテスト環境を Node 14, 16 に更新します

chore: bumpVersion を有効に

---

CHANGELOG.md
package-lock.json
package.json
src/__tests__/AMFlowClientManager.spec.ts
src/play/amflow/AMFlowClient.ts
src/play/amflow/AMFlowStore.ts

掲題どおり。以下を修正します。
- ティックが全くない状態で `getTickList()` するとエラーになる
- 何らかのティックがある状態で、それを全く含まない範囲 (e.g. 未来すぎる) を `getTickList()` すると、得られる `TickList` がおかしい (終了ティックの方が開始ティックより前になるなど)
いずれも期待動作は「TickList として `undefined` が返る」です。当時の設計者の意向により、TickList は [begin, end) ではなく [from, to]  (すなわち終端を含む) になっているため、こうでないと「ティックがない」ことを表現できません。
修正に併せて、対応するユニットテストを追加します。
この問題がこれまで露見しなかったのは、akashic serve (`getTickList()` を使う主要なユーザ) の使い方によるものと想像します。serve は先に runner を生成してからクライアント側のコンテンツを開始するため、時間的に「ティックがない状態で `getTickList()` が呼ばれる」ことが稀だったように思います。

fix: avoid errors on getTickList() for no tick range

---

CHANGELOG.md
package-lock.json
package.json
src/runner/RunnerManager.ts

掲題どおり。
オプションを追加して `Runner#start()` に引き渡します。
内容はほぼ自明で、`start()` の動作そのものは runner.spec.ts で確認されていること、さらに (このクラスを扱っている) run.spec.ts はこの粒度のテストはしていないことから、テストの追加はしていません。

feat: add options for RunnerManager#startRunner()

---

CHANGELOG.md
package.json
src/__tests__/utils.spec.ts
src/utils.ts

掲題どおり。
Windows 環境の akashic serve で、グローバルアセットが 130 程度あるコンテンツを実行した時、 `loadFile()` が失敗してコンテンツを開始できない問題が報告されました。(確認した Windows 11 環境ではロード完了が来ません。また報告では Windows 10 でエラーが返されるとのこと)　この状況では 130 回程度の fetch() が同期的に呼び出されます。
問題を回避するため、キューを設けて同時に実行するロード数を制限します。
akashic serve に組み込み、Windows 11 環境で問題を再現するコンテンツが正しく実行できるようになることを確認しています。

fix: throttle loadFile() to avoid hung on Windows

---

CHANGELOG.md
package-lock.json
package.json
src/runner/v1/platform/assets/NullAudioAsset.ts
src/runner/v1/platform/assets/NullImageAsset.ts
src/runner/v1/platform/assets/NullVideoAsset.ts
src/runner/v2/platform/assets/NullAudioAsset.ts
src/runner/v2/platform/assets/NullImageAsset.ts
src/runner/v2/platform/assets/NullVideoAsset.ts
src/runner/v3/platform/audios/NullAudioAsset.ts
src/runner/v3/platform/graphics/null/NullImageAsset.ts
src/runner/v3/platform/videos/NullVideoAsset.ts

* serveのサーバー(headless-driver)側の画像や音声のアセットのロード処理が同期的だったので、サーバー側もクライアント側と同様にアセットのロードは原則非同期的にするように変更

load assets asynchronously

---

CHANGELOG.md
package-lock.json
package.json
src/runner/v3/RunnerV3.ts
src/runner/v3/platform/graphics/canvas/NodeCanvasRenderer.ts
src/runner/v3/platform/graphics/canvas/NodeCanvasSurface.ts

headless-driver の利用側で canvas の参照エラーとなる import 箇所に `@ts-ignore` を追加。
**動作確認**
npm pack した tgz ファイルを serve で取り込み、tsconfig の skipLibCheck オプションを外してビルドが正常終了することを確認。

Add ignore to import part of canvas

---

.github/workflows/release.yml
.github/workflows/test.yml
src/__tests__/setup.ts

CI の node バージョンを v16, v18 へ更新します。
Node V17からipv6をデフォルトとなったため、`localhost` は `::1` という ipv6アドレスに解決されるためテストでエラーとなった。テストで利用するサーバで ipv6 を利用し ipv6 全てで listen するように修正。
node v18.16.0, v16.19.0 で動作確認。

Support node v18

---

CHANGELOG.md
package-lock.json
package.json
src/__tests__/fixtures/content-v3/assets/exports.js
src/__tests__/fixtures/content-v3/game.json
src/__tests__/fixtures/content-v3/script/main.js
src/__tests__/run.spec.ts
src/runner/v3/platform/NodeCanvasResourceFactory.ts
src/runner/v3/platform/NullResourceFactory.ts

`ScriptAsset` のコンストラクタに `exports` を渡すのを忘れていたため修正します。また今回の修正箇所のテストを追加します。

fix: modify to pass the 'exports' to the constructor

---

CHANGELOG.md
package-lock.json
package.json
src/runner/v3/__tests__/NodeCanvasRenderer.spec.ts
src/runner/v3/platform/graphics/canvas/AffineTransformer.ts
src/runner/v3/platform/graphics/canvas/NodeCanvasContext.ts
src/runner/v3/platform/graphics/canvas/NodeCanvasRenderer.ts
src/runner/v3/platform/graphics/canvas/NodeCanvasSurface.ts
src/runner/v3/platform/graphics/canvas/RenderingState.ts

node-canvas にて、`CanvasRenderingContext2D` の transform で指定するアフィン変換行列の拡大縮小の係数 x, y のいずれかが 0 のときに描画が完全に停止してしまうバグを修正します。
次のミニマムコンテンツを実行したときにプライマリサーフェスの描画が停止しないことを確認
<details>
<summary>展開</summary>
```javascript
const tl = require("@akashic-extension/akashic-timeline");
module.exports = () => {
const game = g.game;
const scene = new g.Scene({
game,
});
const timeline = new tl.Timeline(scene);
scene.onLoad.addOnce(() => {
const rect = new g.FilledRect({
scene,
cssColor: "red",
width: 100,
height: 100,
x: game.width / 2,
y: game.height / 2,
anchorX: 0.5,
anchorY: 0.5,
});
scene.append(rect);
timeline
.create(rect, { loop: true })
.to({ scaleX: 0, scaleY: 0 }, 1000)
.to({ scaleX: 1, scaleY: 1 }, 1000);
});
game.pushScene(scene);
};
```
</details>

fix: fix the bug that the object breaks when rendered at scale 0
