packages/headless-driver-runner-v1/package.json
packages/headless-driver-runner-v2/package.json

内部コンポーネントの更新

---

lerna.json

内部モジュールの更新 ( #6 ) をバージョン更新対象に含めるため、 `*.json` を `ignoreChanges` から削除します。

Drop *.json from ignoreChanges

---

.travis.yml

travis-ci のテスト環境に windows を追加します。

Add `windows` and drop Node v6 to .travis.yml

---

package-lock.json
packages/headless-driver-runner-v1/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver-runner-v2/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver/src/__tests__/contents/content-v1/script/main.js
packages/headless-driver/src/__tests__/contents/content-v2/script/main.js

Script asset の末尾に line comment が存在した場合、スクリプトの実行に失敗していたバグを修正します。

Fix to execute script when trailing line comment

---

CHANGELOG.md
packages/headless-driver/src/index.ts

#23 にて追加した `Content` を entry point から export するようにします。

Export Content Interface

---

packages/headless-driver-runner-v2/package.json

【v0.4.3】内部コンポーネントの更新(engineFiles@2.1.17, engineFiles@1.1.9)

---

packages/headless-driver-runner-v2/package.json

【v0.4.3】内部コンポーネントの更新(engineFiles@2.1.18, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package-lock.json
packages/headless-driver-runner-v2/package-lock.json
packages/headless-driver/src/play/Content.ts

以下を export します。
* `ContentParameters`
* `GameJsonParameters`

Export ContentParameters and GameJsonParameters

---

package.json

lerna-changelog の生成する label に `dependencies` を追加します。

Add `dependencies` label to lerna-changelog

---

packages/headless-driver-runner-v2/package-lock.json
packages/headless-driver-runner-v2/package.json

【v0.4.4】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package-lock.json
packages/headless-driver-runner-v2/package-lock.json

【v0.4.5】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package-lock.json
packages/headless-driver-runner-v2/package-lock.json

【v0.4.6】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package-lock.json
packages/headless-driver-runner-v2/package-lock.json

【v0.4.7】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package-lock.json
packages/headless-driver-runner-v2/package-lock.json

【v0.4.8】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package-lock.json
packages/headless-driver-runner-v2/package-lock.json

【v0.4.9】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package-lock.json
packages/headless-driver-runner-v2/package-lock.json

【v0.4.10】内部コンポーネントの更新(engineFiles@2.1.19, engineFiles@1.1.9)

---

packages/headless-driver-runner-v1/package.json
packages/headless-driver-runner-v2/package.json

* engineFilesV2: 2.1.22
* engineFilesV1: 1.1.10

【v0.4.12】内部コンポーネントの更新(engineFiles@2.1.22, engineFiles@1.1.10)

---

packages/headless-driver-runner-v1/package.json

* engineFilesV2: 2.1.22
* engineFilesV1: 1.1.11

【v0.5.1】内部コンポーネントの更新(engineFiles@2.1.22, engineFiles@1.1.11)

---

packages/headless-driver-runner-v1/package.json

【v0.5.4】内部コンポーネントの更新(engineFiles@2.1.24, engineFiles@1.1.12)

---

packages/headless-driver-runner-v2/package.json

【v0.5.10】内部コンポーネントの更新(engineFiles@2.1.30, engineFiles@1.1.12)

---

packages/headless-driver/package.json

##　修正内容
pacakge.json の`devDependencies` に 定義されていた `vm2` を `dependencies` へ移動します

Fix vm2 of package.json to dependencies

---

packages/headless-driver-runner-v2/package.json

【v0.5.14】内部コンポーネントの更新(engineFiles@2.1.32, engineFiles@1.1.12)

---

packages/headless-driver-runner-v1/package.json

* engineFilesV2: 2.1.32
* engineFilesV1: 1.1.13

【v0.5.15】内部コンポーネントの更新(engineFiles@2.1.32, engineFiles@1.1.13)

---

packages/headless-driver-runner-v2/package.json

* engineFilesV2: 2.1.34
* engineFilesV1: 1.1.13
* playlog: 1.3.3
* trigger: 0.1.6

【v0.5.17】内部コンポーネントの更新(engineFiles@2.1.34, engineFiles@1.1.13)

---

packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

`headless-driver` の `AMFlow` に `playLog`をdumpする機能を追加。

Add dump function to AMFlow

---

.travis.yml

travisの対象からnode-v8を削除し、v12を追加します。

Remove node-8 from travis.yml and add node-12

---

.travis.yml

travis.ymlの対象からnode8を削除し、node12を追加

Remvoe node8 from travis and add node12

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 3.0.0-beta.2
* engineFilesV2: 2.1.38

【v1.0.2】内部コンポーネントの更新(engineFiles@3.0.0-beta.2, engineFiles@2.1.38, engineFiles@1.1.14)

---

packages/headless-driver-runner-v3/package.json
packages/headless-driver-runner-v3/src/platform/NullAudioPlayer.ts
packages/headless-driver-runner-v3/src/platform/NullVideoPlayer.ts

内部コンポーネントを更新します。 engine-files@3.0.0-beta.3 に追従したのみ。
* engineFilesV3: 3.0.0-beta.3
* engineFilesV2: 2.1.38

【v1.1.3】内部コンポーネントの更新(engineFiles@3.0.0-beta.3, engineFiles@2.1.38, engineFiles@1.1.14) 

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 3.0.0-beta.3
* engineFilesV2: 2.1.39

【v1.1.4】内部コンポーネントの更新(engineFiles@3.0.0-beta.3, engineFiles@2.1.39, engineFiles@1.1.14)

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.0-beta.5
* engineFilesV2: 2.1.39

【v1.1.7】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.39, engineFiles@1.1.14)

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 3.0.0-beta.5
* engineFilesV2: 2.1.40

【v1.1.8】内部コンポーネントの更新(engineFiles@3.0.0-beta.5, engineFiles@2.1.40, engineFiles@1.1.14)

---

.npmrc
packages/headless-driver-runner-v1/.npmrc
packages/headless-driver-runner-v2/.npmrc
packages/headless-driver-runner-v3/.npmrc
packages/headless-driver-runner-v3/package.json
packages/headless-driver-runner-v3/src/platform/NullAudioPlayer.ts
packages/headless-driver-runner-v3/src/platform/NullGlyph.ts
packages/headless-driver-runner-v3/src/platform/NullGlyphFactory.ts
packages/headless-driver-runner-v3/src/platform/NullRenderer.ts
packages/headless-driver-runner-v3/src/platform/NullSurface.ts
packages/headless-driver-runner-v3/src/platform/NullSurfaceAtlas.ts
packages/headless-driver-runner-v3/src/platform/NullVideoPlayer.ts
packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
packages/headless-driver-runner-v3/src/platform/ResourceFactory.ts
packages/headless-driver-runner-v3/src/platform/assets/Asset.ts
packages/headless-driver-runner-v3/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NodeTextAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NullAudioAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NullImageAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NullVideoAsset.ts
packages/headless-driver-runner/.npmrc
packages/headless-driver-runner/package.json
packages/headless-driver/.npmrc
packages/headless-driver/package.json
packages/headless-driver/src/__tests__/AMFlowSpec.ts
packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

* `@akashic/engine-files@3.0.0-beta.6` に対応します
* [transient event](https://github.com/akashic-games/playlog/pull/6) に対応します

Follow @akashic/engine-files@3.0.0-beta.6

---

.npmrc
packages/headless-driver-runner-v1/.npmrc
packages/headless-driver-runner-v1/package.json
packages/headless-driver-runner-v2/.npmrc
packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/.npmrc
packages/headless-driver-runner-v3/package.json
packages/headless-driver-runner-v3/src/platform/NullAudioPlayer.ts
packages/headless-driver-runner-v3/src/platform/NullGlyph.ts
packages/headless-driver-runner-v3/src/platform/NullGlyphFactory.ts
packages/headless-driver-runner-v3/src/platform/NullRenderer.ts
packages/headless-driver-runner-v3/src/platform/NullSurface.ts
packages/headless-driver-runner-v3/src/platform/NullSurfaceAtlas.ts
packages/headless-driver-runner-v3/src/platform/NullVideoPlayer.ts
packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
packages/headless-driver-runner-v3/src/platform/ResourceFactory.ts
packages/headless-driver-runner-v3/src/platform/assets/Asset.ts
packages/headless-driver-runner-v3/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NodeTextAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NullAudioAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NullImageAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NullVideoAsset.ts
packages/headless-driver-runner/.npmrc
packages/headless-driver-runner/package.json
packages/headless-driver/.npmrc
packages/headless-driver/package.json
packages/headless-driver/src/__tests__/AMFlowSpec.ts
packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

* engineFilesV3: 3.0.0-beta.6
* engineFilesV2: 2.1.41
* engineFilesV1: 1.1.15
* amflow: 2.0.0
* playlog: 3.0.0

【v1.1.19】内部コンポーネントの更新(engineFiles@3.0.0-beta.6, engineFiles@2.1.41, engineFiles@1.1.15)

---

packages/headless-driver-runner-v3/package.json
packages/headless-driver-runner/package.json
packages/headless-driver/package.json
packages/headless-driver/src/__tests__/AMFlowSpec.ts
packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

以下のモジュール更新に対応します。
* https://github.com/akashic-games/playlog/pull/8
* https://github.com/akashic-games/amflow/pull/8

Follow amflow@3.0.0 (supports ignorable event)

---

packages/headless-driver-runner-v1/package.json
packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/package.json
packages/headless-driver-runner/package.json
packages/headless-driver/package.json
packages/headless-driver/src/__tests__/AMFlowSpec.ts
packages/headless-driver/src/play/amflow/AMFlowClient.ts
packages/headless-driver/src/play/amflow/AMFlowStore.ts

* engineFilesV3: 3.0.0-beta.7
* engineFilesV2: 2.1.46

【v1.1.27】内部コンポーネントの更新(engineFiles@3.0.0-beta.7, engineFiles@2.1.46, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.0-beta.9
* engineFilesV2: 2.1.47

【v1.2.11】内部コンポーネントの更新(engineFiles@3.0.0-beta.9, engineFiles@2.1.47, engineFiles@1.1.16)

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
packages/headless-driver-runner/src/Looper.ts
packages/headless-driver/src/__tests__/AMFlowSpec.ts
packages/headless-driver/src/runner/RunnerManager.ts

Looper を一時的に停止/再開させるメソッド `pause` `resume` を追加します。
- なし

add Looper#step/resume for pause looper

---

.npmrc
lerna.json
package-lock.json
packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
packages/headless-driver-runner/src/Runner.ts
packages/headless-driver/src/__tests__/fixtures/content-v1/script/main.js
packages/headless-driver/src/__tests__/fixtures/content-v2/script/main.js
packages/headless-driver/src/__tests__/fixtures/content-v3/script/main.js
packages/headless-driver/src/__tests__/runSpec.ts

コンテンツに任意のポイントイベントを送信するために `Runner#firePointEvent()` を追加します。

feat: add Runner#firePointEvent()

---

packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.1
* engineFilesV2: 2.1.50

【v1.5.1】内部コンポーネントの更新(engineFiles@3.0.1, engineFiles@2.1.50, engineFiles@1.1.16)

---

packages/headless-driver-runner/src/Looper.ts
packages/headless-driver-runner/src/Platform.ts
packages/headless-driver-runner/src/Runner.ts
packages/headless-driver-runner/tsconfig.json

https://github.com/akashic-games/headless-driver/pull/208 の分割PRです。
`strict: true` を有効にします。
strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。
PRの範囲からあふれる修正は次の課題とします。

use strict, headless-driver-runner

---

packages/headless-driver-runner-v1/src/RunnerV1.ts
packages/headless-driver-runner-v1/src/platform/PlatformV1.ts
packages/headless-driver-runner-v1/src/platform/assets/NullImageAsset.ts
packages/headless-driver-runner-v1/src/platform/assets/NullVideoAsset.ts
packages/headless-driver-runner-v1/tsconfig.json

https://github.com/akashic-games/headless-driver/pull/208 の分割PRです。
`strict: true` を有効にします。
strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。
PRの範囲からあふれる修正は次の課題とします。

use strict, headless-driver-runner-v1

---

packages/headless-driver-runner-v2/src/RunnerV2.ts
packages/headless-driver-runner-v2/src/platform/NullRenderer.ts
packages/headless-driver-runner-v2/src/platform/PlatformV2.ts
packages/headless-driver-runner-v2/src/platform/assets/NullImageAsset.ts
packages/headless-driver-runner-v2/src/platform/assets/NullVideoAsset.ts
packages/headless-driver-runner-v2/tsconfig.json

https://github.com/akashic-games/headless-driver/pull/208 の分割PRです。
`strict: true` を有効にします。
strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。
PRの範囲からあふれる修正は次の課題とします。

use strict, headless-driver-runner-v2

---

packages/headless-driver-runner-v3/src/RunnerV3.ts
packages/headless-driver-runner-v3/src/__tests__/NodeCanvasGlyphFactory.spec.ts
packages/headless-driver-runner-v3/src/__tests__/NodeCanvasImageAsset.spec.ts
packages/headless-driver-runner-v3/src/__tests__/NodeCanvasRenderer.spec.ts
packages/headless-driver-runner-v3/src/platform/PlatformV3.ts
packages/headless-driver-runner-v3/src/platform/assets/Asset.ts
packages/headless-driver-runner-v3/src/platform/assets/NodeScriptAsset.ts
packages/headless-driver-runner-v3/src/platform/assets/NodeTextAsset.ts
packages/headless-driver-runner-v3/src/platform/audios/NullAudioPlayer.ts
packages/headless-driver-runner-v3/src/platform/graphics/null/NullImageAsset.ts
packages/headless-driver-runner-v3/src/platform/graphics/null/NullRenderer.ts
packages/headless-driver-runner-v3/src/platform/graphics/null/NullSurface.ts
packages/headless-driver-runner-v3/src/platform/videos/NullVideoAsset.ts
packages/headless-driver-runner-v3/src/platform/videos/NullVideoPlayer.ts
packages/headless-driver-runner-v3/tsconfig.json

https://github.com/akashic-games/headless-driver/pull/208 の分割PRです。
`strict: true` を有効にします。
strcit下で全体のビルドを通す、可能な是正箇所の修正を扱います。
PRの範囲からあふれる修正は次の課題とします。

use strict, headless-driver-runner-v3

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.2
* engineFilesV2: 2.1.50

【v1.5.3】内部コンポーネントの更新(engineFiles@3.0.2, engineFiles@2.1.50, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.3
* engineFilesV2: 2.1.50

【v1.5.3】内部コンポーネントの更新(engineFiles@3.0.3, engineFiles@2.1.50, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.4
* engineFilesV2: 2.1.50

【v1.5.4】内部コンポーネントの更新(engineFiles@3.0.4, engineFiles@2.1.50, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.9
* engineFilesV2: 2.1.52

【v1.5.9】内部コンポーネントの更新(engineFiles@3.0.9, engineFiles@2.1.52, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.5.12】内部コンポーネントの更新(engineFiles@3.0.11, engineFiles@2.1.53, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.5.13】内部コンポーネントの更新(engineFiles@3.0.12, engineFiles@2.1.53, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.5.14】内部コンポーネントの更新(engineFiles@3.0.13, engineFiles@2.1.53, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.5.15】内部コンポーネントの更新(engineFiles@3.0.14, engineFiles@2.1.53, engineFiles@1.1.16)

---

packages/headless-driver-runner-v2/package.json
packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.15
* engineFilesV2: 2.1.54

【v1.7.3】内部コンポーネントの更新(engineFiles@3.0.15, engineFiles@2.1.54, engineFiles@1.1.16)

---

packages/headless-driver-runner-v2/package.json

* engineFilesV3: 3.0.19
* engineFilesV2: 2.1.56

【v1.8.4】内部コンポーネントの更新(engineFiles@3.0.19, engineFiles@2.1.56, engineFiles@1.1.16)

---

packages/headless-driver/src/__tests__/renderer.spec.ts
packages/headless-driver/src/__tests__/runner.spec.ts

特定の CI 環境で落ちる一部のテストををスキップするようにします。
(CI環境で何回か動かし正常終了する事は確認済み)

Disable some tests

---

packages/headless-driver-runner-v3/package.json

* engineFilesV3: 3.0.20
* engineFilesV2: 2.1.56

【v1.9.1】内部コンポーネントの更新(engineFiles@3.0.20, engineFiles@2.1.56, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.9.3】内部コンポーネントの更新(engineFiles@3.0.21, engineFiles@2.1.57, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.10.1】内部コンポーネントの更新(engineFiles@3.1.1, engineFiles@2.1.57, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

【v1.11.1】内部コンポーネントの更新(engineFiles@3.1.3, engineFiles@2.1.57, engineFiles@1.1.16)

---

packages/headless-driver-runner-v3/package.json

※本PRは自動生成されたものです\n\n* engineFilesV3: 3.1.4\n* engineFilesV2: 2.1.57\n* engineFilesV1: 1.1.16\n* amflow: 3.1.0\n* playlog: 3.1.0\n* trigger: 1.0.0\n\n

【v1.11.10】内部コンポーネントの更新(engineFiles@3.1.4, engineFiles@2.1.57, engineFiles@1.1.16)

---

.github/workflows/release.yml
.github/workflows/test.yml

* リリース用のワークフローを追加します。
* `actions/cache` を削除して `actions/setup-node` で行うように変更します。

chore(ci): リリースのワークフローを追加

---

packages/headless-driver-runner-v3/package.json

【v1.11.23】内部コンポーネントの更新(engineFiles@3.1.5, engineFiles@2.1.57, engineFiles@1.1.16)

---

.github/workflows/release.yml
.github/workflows/test.yml

main ブランチへとマージされたタイミングで release を行うワークフローを追加します。
1. prepare-2.0.0 ブランチへとマージ後 main ブランチへと改名
2. headless-driver@2.0.0-beta.0 の release
3. 動作確認して問題なければ prerelease の削除

chore: リリースワークフローの追加

---

package-lock.json
package.json

Reverts akashic-games/headless-driver#407
マージされていはいけない PullRequest がなぜかマージされてしまったので revert します。

Revert "fix(deps): update dependency aev2 to v3"

---

CHANGELOG.md
package-lock.json
package.json

chore: version 2.0.1

---

CHANGELOG.md
package-lock.json
package.json

engine-files@3.1.9 への更新を publish します。

chore: version 2.0.2

---

.editorconfig
package-lock.json
package.json

依存モジュールのバージョン範囲を `^` に変更

---

CHANGELOG.md
package-lock.json
package.json
src/runner/v3/platform/graphics/canvas/NodeCanvasGlyphFactory.ts
src/runner/v3/platform/graphics/canvas/NodeCanvasRenderer.ts

canvas を optionalDependencies から devDependencies へ変更

Mod canvas to devdependencies

---

package-lock.json
package.json

個別に行うとビルドが壊れる #630, #636, #637 を一括で行います。
自明につきセルフマージします。

fix(deps): update dependency engine-files-v1,v2,v3

---

CHANGELOG.md
package-lock.json
package.json
src/TimeKeeper.ts
src/__tests__/constants.ts
src/__tests__/fixtures/content-v1/script/main.js
src/__tests__/fixtures/content-v2/script/main.js
src/__tests__/fixtures/content-v3/script/main.js
src/__tests__/helpers/constants.ts
src/__tests__/play.spec.ts
src/__tests__/renderer.spec.ts
src/__tests__/run.spec.ts
src/__tests__/runner.spec.ts
src/runner/Platform.ts
src/runner/Runner.ts
src/runner/RunnerManager.ts
src/runner/types.ts
src/runner/v1/RunnerV1.ts
src/runner/v1/platform/assets/NullAudioAsset.ts
src/runner/v1/platform/assets/NullImageAsset.ts
src/runner/v1/platform/assets/NullVideoAsset.ts
src/runner/v2/RunnerV2.ts
src/runner/v2/platform/assets/NullAudioAsset.ts
src/runner/v2/platform/assets/NullImageAsset.ts
src/runner/v2/platform/assets/NullVideoAsset.ts
src/runner/v3/RunnerV3.ts
src/runner/v3/platform/audios/NullAudioAsset.ts
src/runner/v3/platform/graphics/null/NullImageAsset.ts
src/runner/v3/platform/videos/NullVideoAsset.ts

feat: support replay mode

---

CHANGELOG.md
package-lock.json
package.json

engine-files@3.12.0 の更新に伴いマイナーバージョンの更新。

Bump version 2.17.0
